version: 2

models:
  - name: stg_job_ads
  - name: dim_occupation
  - name: dim_employer
  - name: dim_job_details
  - name: dim_auxilliary_attributes
  - name: fct_job_ads
  - name: sales_mart
  - name: health_mart
  - name: hospitality_mart