with job_details as (
    select *
   from {{ source('job_ads', 'job_ads_all') }}

)

select
 id,
    external_id,
    label,
    webpage_url,
    headline,
    relevance,
    application_deadline,
    number_of_vacancies,
    description__text,
    description__text_formatted,
    employment_type__concept_id,
    employment_type__label,
    employment_type__legacy_ams_taxonomy_id,
    salary_type__concept_id,
    salary_type__label,
    salary_type__legacy_ams_taxonomy_id,
    duration__concept_id,
    duration__label,
    duration__legacy_ams_taxonomy_id,
    working_hours_type__concept_id,
    working_hours_type__label,
    working_hours_type__legacy_ams_taxonomy_id,
    scope_of_work__min,
    scope_of_work__max,
    employer__url,
    employer__organization_number,
    employer__name,
    employer__workplace,
    application_details__via_af,
    application_details__url,
    experience_required,
    access_to_own_car,
    driving_license_required,
    occupation__concept_id,
    occupation__label,
    occupation__legacy_ams_taxonomy_id,
    occupation_group__concept_id,
    occupation_group__label,
    occupation_group__legacy_ams_taxonomy_id,
    occupation_field__concept_id,
    occupation_field__label,
    occupation_field__legacy_ams_taxonomy_id,
    workplace_address__municipality,
    workplace_address__municipality_code,
    workplace_address__municipality_concept_id,
    workplace_address__region,
    workplace_address__region_code,
    workplace_address__region_concept_id,
    workplace_address__country,
    workplace_address__country_code,
    workplace_address__country_concept_id,
    publication_date,
    last_publication_date,
    removed,
    source_type,
    timestamp,
    occupation_field_name,
    _dlt_load_id,
    _dlt_id,
    description__conditions,
    salary_description,
    application_details__information,
    application_details__reference,
    logo_url,
    workplace_address__street_address,
    workplace_address__postcode,
    workplace_address__city,
    application_details__email,
    application_details__other

from job_details
