name: hr_analytics_dbt
version: 1.0.0
config-version: 2

profile: HR_Analytics_Proof_of_Concept_Group_2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

quoting:
  database: false
  schema: true
  identifier: true


models:
  hr_analytics_dbt:
    +materialized: view

    src:
      +schema: staging
      materialized: ephemeral

    dim:
      +schema: refined

    fct:
      +schema: refined

    mart:
      +schema: mart